from typing import Optional
from agents.Agent import Agent
from utils import extract_json_from_string

SYSTEM_PROMPT = """
Your task is to generate critical questions. The user will provide you with an argument, and you solely reply with a single critical question.
"""

GENERATION_PROMPT = """
Generate a critical question for the following argument:

'{argument}'

Strictly return your critical question in the following JSON format:  
```json
{{
  'critial_question': <your generated critical question>,
}}
```

"""


class GeneratorAgent(Agent):
    def __init__(
        self,
        argument: str,
        model_name: str,
        model_parameters: dict = {},
    ):
        super().__init__(model_name, model_parameters)

        # Agent specific parameters
        self.argument = argument
        self.model_name = model_name

    def _initialize(self):
        # Initialize system prompt
        message = SYSTEM_PROMPT
        self._add_to_chat(role="system", message=message)

    def _generate_critical_question(self) -> Optional[str]:
        """Generates a critical question for the given argument.

        Returns:
            str: The critical question generated by the agent.
        """
        # Create the prompt and add to chat
        prompt = GENERATION_PROMPT.format(argument=self.argument)
        self._add_to_chat(role="user", message=prompt)

        # Prompt LLM and add to chat
        response = self.single_response(messages=self.chat)
        self._add_to_chat(role="assistant", message=response)

        # Process response and return
        response_dict: dict = extract_json_from_string(response)
        critical_question = response_dict.get("critical_question", None)
        if not critical_question:
            print(
                "Error: LLM returned an invalid response. Expected JSON with key 'critical_question', but no JSON with that key was found."
            )
            # TODO Implement some retries here.
        return critical_question

    def generate_critical_question(self) -> str:
        # Generate a critical question
        critical_question = self._generate_critical_question()

        # Return initial or refined critical question
        return critical_question
